version: '3.9'
services:
    trading-bot:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        env_file:
            - ../.env
        volumes:
            - ../database:/app/database
        restart: always
